import '~/styles/globals.css';

import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { Suspense } from 'react';
import theme from '../ui/theme';
import { TRPCReactProvider } from '~/trpc/react';
import { ClientProviders } from '~/components/utils/ClientProviders';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className={GeistSans.className}>
        <TRPCReactProvider>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <Suspense fallback={<div>Loading...</div>}>
                <ClientProviders>{children} </ClientProviders>
              </Suspense>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
