import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Suspense } from "react";
import { TRPCReactProvider } from "~/trpc/react";
import { ClientProviders } from "~/components/utils/client-providers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <TRPCReactProvider>
          <Suspense fallback={<div>Loading...</div>}>
            <ClientProviders>{children} </ClientProviders>
          </Suspense>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
