/* eslint-disable @next/next/no-img-element */
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CXc7Te1Marj
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { SurveyUploadForm } from "./modules/survey-upload-form";
import { getServerAuthSession } from "~/server/auth";

export async function HomeContent() {
  const session = await getServerAuthSession();

  return (
    <div className="flex w-full flex-col items-center space-y-8 p-4">
      <header className="flex flex-col items-center space-y-4">
        <h1 className="text-center text-4xl font-bold">STRIXY</h1>
        <h1 className="text-center text-4xl font-bold">
          Survey analytics redefined
        </h1>
        <p className="text-center text-lg">
          Strixy <span className="text-blue-600">analyses</span> the{" "}
          <span className="text-red-600">feedback</span> of your{" "}
          <span className="text-orange-600">clients</span> and{" "}
          <span className="text-green-600">summarizes</span> it for you
        </p>
        <div className="flex flex-wrap justify-center space-x-2 text-center text-sm">
          {/* <span className="text-blue-600">reads</span>
          <span className="text-blue-600">interprets</span>
          <span className="text-purple-600">testimonies</span>
          <span className="text-purple-600">reviews</span>
          <span className="text-orange-600">customers</span>
          <span className="text-orange-600">users</span>
          <span className="text-blue-600">classifies</span>
          <span className="text-blue-600">understands</span>
          <span className="text-purple-600">complaints</span>
          <span className="text-purple-600">suggestions</span>
          <span className="text-orange-600">staff</span>
          <span className="text-orange-600">students</span>
          <span className="text-green-600">explains</span>
          <span className="text-green-600">takes action on</span> */}
        </div>
      </header>
      <section className="text-center">
        <h2 className="text-2xl font-semibold">Experiment now for free!</h2>
        <p className="mt-2 text-lg">
          Upload a CSV file in any format with the survey remarks you want
          analyzed and provide a brief context. We’ll generate an AI-powered
          report and send it directly to your email.
        </p>
      </section>
      <section className="w-full max-w-xl rounded-md border p-4">
        <SurveyUploadForm defaultEmail={session?.user.email ?? undefined} />
      </section>

      <section className="text-center">
        <h2 className="text-2xl font-semibold">Want to see an example?</h2>
        <div className="mt-4 flex flex-wrap justify-center space-x-8">
          <div className="flex flex-col items-center space-y-2">
            <img
              src="/placeholder.svg"
              alt="Original file"
              className="h-48 w-64"
              width="300"
              height="200"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <p>
              Original file containing remarks of students in an university:
            </p>
          </div>
          <div className="flex flex-col items-center space-y-2">
            <img
              src="/placeholder.svg"
              alt="Result file"
              className="h-48 w-64"
              width="300"
              height="200"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <p>
              Result file with auto-generated information such as “topic” and
              “sentiment” for each remark…
            </p>
          </div>
          <div className="flex flex-col items-center space-y-2">
            <img
              src="/placeholder.svg"
              alt="Statistics"
              className="h-48 w-64"
              width="300"
              height="200"
              style={{ aspectRatio: "300/200", objectFit: "cover" }}
            />
            <p>…and some statistics</p>
          </div>
        </div>
      </section>
    </div>
  );
}
